################################################################################
# Docker Compose file for running the API and MongoDB
################################################################################

services:
  # API service
  api:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped
    environment:
      - API_VERSION=${API_VERSION}
      - ENVIRONMENT=${ENVIRONMENT}
      - APP_NAME=${APP_NAME}
      - APP_DESCRIPTION=${APP_DESCRIPTION}
      - MONGODB_URI=${MONGO_URI}/${MONGO_DATABASE}
      - PORT=${PORT}
    depends_on:
      - mongodb
    networks:
      - naqa-network
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - naqa-network

# Networks
networks:
  naqa-network:
    driver: bridge

# Volumes
volumes:
  mongodb_data: