services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGO_URI}/${MONGO_DATABASE}
      - PORT=${PORT}
    depends_on:
      - mongodb
    networks:
      - naqa-network

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - naqa-network

networks:
  naqa-network:
    driver: bridge

volumes:
  mongodb_data: